project:
  type: website
  output-dir: docs

website:
  title: "EC338"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Lectures
        menu:
          - href: lecture-1-1.qmd
            text: Lecture 1.1
          - href: lecture-1-2.qmd
            text: Lecture 1.2
      - text: Seminars
        menu:
          - href: seminar-1.qmd
            text: Seminar 1 
          - href: seminar-3.qmd
            text: Seminar 3     
      - text: Additional
        menu:
          - href: material-cef.qmd
            text: Conditional Expectation Function 
          - href: material-linearalgebra.qmd
            text: Linear Algebra
            
bibliography: references.bib

format:
  html:
    theme: 
      light: lightly
      dark: darkly
    css: styles.css
    toc: true

editor: source

execute:
  freeze: auto
  
