---
title: "Econometrics 2: Microeconometrics"
---

## Welcome to '338!

This is not the official module website. The [EC338 (2024/25)](https://moodle.warwick.ac.uk/course/view.php?id=64246) Moodle-page is the primary source of communication and resources for this module. All material available on this website can be found there.

I designed this website as a means of testing out the Quarto package, developed by RStudio.[^1] This was partly as a way to develop my own skills and better incorporate the R language into the module. However, there are also accessibility benefits to this approach. Mathematical notation published in pdf's using LaTeX cannot be read by a screen reader, while LaTeX published in html can. In addition, the website has built-in dark-mode option (see top-right toggle). For those who prefer pdf (for printing and notetaking), each page contains a unique downloadable link.

[^1]: To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

## Acknowledgements

I would like to thank the following students for their help with this and other pedagogical projects: Diwen Si (BSc, 2023/24); Franklin Gonzalez Alcantara (BSc, 2023/24); Milan Makany (MSc, 2023/24); Jiarui Song (BSc, 2022/23); Patricio Hernandez Senosiain (BSc, 2022/23); Takumi Horikawa (MSc, 2022/23). You have been instrumental in my learning as well as the learning of the many students who will use these resources going forward.

**Please let me know if you find any mistakes in my notes or code.** In addition, I welcome suggestions on how to improve the R (or Stata) code provided in this module. I will endeavor to do my best to acknowledge the many people who have contributed to this material and my wider knowledge of this subject.

## Source Material

My material for EC338 has been heavily influenced by @imbens2015 seminal book on causal inference, *Causal Inference in Statistics, Social, and Biomedical Sciences*. This book is dense and comprehensive, having been written for a wide range of scientists. It includes discussions on topics that are less relevant in economics research. I have borrowed extensively from @imbens2015 in my discussions of the Potential Outcomes Framework and randomized experiments, adopting much of their notation. The text is less relevant to natural experiment methodologies like difference-in-differences, but I have tried to maintain a consistent notation throughout.

There are a number of texts more readily used by applied economists. In particular, @angrist2009 *Mostly Harmless Econometrics*, a text that became a must-read for all applied microeconomics researchers during the last 15 years. In *Mostly Harmless*, @angrist2009 try to provide a practical guide to the use and interpretation of Econometric methods in applied microeconomics research. They focus on methods used *by Economists* in the study of randomized and natural experiments. This is both a strength and weakness of the book, as the content is largely based on practice (i.e. the methods being used by economists) which need not be "best practice". As such, the book has the same shortcomings and biases as the economics discipline. For example, economists like linear regression models, but as we will soon see there are problems associated with the application of these models in a setting with heterogeneous treatment effects.

In my opinion, @angrist2009 is better suited to graduate students who have a more extensive knowledge of Econometric methods. Some of the Econometrics topics discussed as well as the notation used, is not typically covered in an undergraduate syllabus. Fortunately, Angrist has provided a less technical version, *Mastering 'Metrics* [@angrist2014], focused on intuition and application.

Another modern text that includes helpful code and examples is @cunningham2021 *Causal Inference: The Mixtape*. This book provides an excellent discussion of modern applied methods; especially topics related to the study of observational data (e.g., matching) and natural experiments (incl., DID, RDD, Event-studies). The discussion on difference-in-differences references some of the more recent literature related to heterogeneous effects.

My notes try to provide a more theoretical foundation to the discussion of causal inference in Econometrics, something that I feel is missing in @angrist2009 and @cunningham2021. To do so, I borrow from @imbens2015, whose discussion of causal effects is based on an experimental model of the data generating process. This experimental foundation is not always consistent with the econometrics models studied in standard Econometric texts [see @wooldridge2010]. In my notes, I try to provide an introduction to the experimental model as well as a bridge to the econometrics models you are already familiar with (mostly linear regression model). But this bridge doesn't always exist and, when it does, it sometimes takes a toll (i.e. additional assumptions).

**I hope you enjoy this module!**

[Neil Lloyd](https://warwick.ac.uk/fac/soc/economics/staff/nlloyd/)

## References
